---
- hosts: 172.31.39.216
  become: yes
  tasks:
  - include_tasks: fileextension.yml
  - name: i want to create folder in node
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: copy file from master to node
    copy:
     src: mymasterfile.txt
     dest: /home/ubuntu/mymasterfile
     
